# Generated by Django 3.0.8 on 2020-07-04 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SusiJH',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='전형명')),
            ],
            options={
                'verbose_name': '수시전형',
                'verbose_name_plural': '수시전형',
            },
        ),
        migrations.CreateModel(
            name='SusiMajor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='학과명')),
                ('susi_jh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='susi_majors', to='univ.SusiJH', verbose_name='수시전형')),
            ],
            options={
                'verbose_name': '수시 학과',
                'verbose_name_plural': '수시 학과',
            },
        ),
        migrations.CreateModel(
            name='Univ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='대학명')),
                ('logo', models.ImageField(blank=True, upload_to='', verbose_name='로고 이미지')),
                ('review_url', models.CharField(blank=True, max_length=100, verbose_name='리뷰 URL')),
            ],
            options={
                'verbose_name': '대학',
                'verbose_name_plural': '대학',
            },
        ),
        migrations.CreateModel(
            name='SusiSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, verbose_name='일정 설명')),
                ('start_date', models.DateTimeField(verbose_name='시작 시간')),
                ('end_date', models.DateTimeField(verbose_name='종료 시간')),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='susi_schedules', to='univ.SusiMajor', verbose_name='수시 학과')),
            ],
            options={
                'verbose_name': '수시 일정',
                'verbose_name_plural': '수시 일정',
            },
        ),
        migrations.AddField(
            model_name='susijh',
            name='univ',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='susi_jhs', to='univ.Univ', verbose_name='대학'),
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(max_length=50, verbose_name='기기 ID')),
                ('susis', models.ManyToManyField(related_name='devices', to='univ.SusiMajor', verbose_name='즐찾 수시')),
            ],
            options={
                'verbose_name': '기기 정보',
                'verbose_name_plural': '기기 정보',
            },
        ),
    ]
