# Generated by Django 3.0.8 on 2020-07-01 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jeonhyeong',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('susi_jeongsi', models.CharField(choices=[('수시', '수시'), ('정시', '정시')], max_length=7, verbose_name='수시/정시')),
                ('name', models.CharField(max_length=63, verbose_name='전형명')),
                ('year', models.IntegerField(choices=[(2021, 2021)], verbose_name='학년도')),
            ],
            options={
                'verbose_name': '전형',
                'verbose_name_plural': '전형',
            },
        ),
        migrations.CreateModel(
            name='MajorBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('susi_jeongsi', models.CharField(choices=[('수시', '수시'), ('정시', '정시')], max_length=7, verbose_name='수시/정시')),
                ('name', models.CharField(max_length=255, verbose_name='분류명')),
            ],
            options={
                'verbose_name': '학과 블록',
                'verbose_name_plural': '학과 블록',
            },
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=63, unique=True, verbose_name='대학명')),
                ('logo', models.ImageField(blank=True, upload_to='', verbose_name='로고 이미지')),
                ('review_url', models.CharField(blank=True, max_length=127, verbose_name='리뷰 URL')),
            ],
            options={
                'verbose_name': '대학',
                'verbose_name_plural': '대학',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university', models.CharField(editable=False, max_length=63)),
                ('year', models.IntegerField(editable=False)),
                ('sj', models.CharField(editable=False, max_length=7)),
                ('jh', models.CharField(editable=False, max_length=63)),
                ('block', models.CharField(editable=False, max_length=255)),
                ('description', models.CharField(max_length=255, verbose_name='설명')),
                ('start_date', models.DateTimeField(verbose_name='시작시간')),
                ('end_date', models.DateTimeField(verbose_name='종료시간')),
                ('jeonhyeong', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='univ.Jeonhyeong', verbose_name='전형')),
                ('major_block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='univ.MajorBlock', verbose_name='학과 블록')),
            ],
            options={
                'verbose_name': '일정',
                'verbose_name_plural': '일정',
            },
        ),
        migrations.AddField(
            model_name='majorblock',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='major_blocks', to='univ.University', verbose_name='대학'),
        ),
        migrations.AddField(
            model_name='jeonhyeong',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jeonhyeongs', to='univ.University', verbose_name='대학'),
        ),
    ]
