# Generated by Django 3.0.8 on 2020-07-04 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('univ', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='univ',
            name='logo',
            field=models.CharField(blank=True, max_length=100, verbose_name='로고 URL'),
        ),
    ]
