# Generated by Django 3.0.8 on 2020-07-04 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('univ', '0002_auto_20200704_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='unique_id',
            field=models.CharField(max_length=50, unique=True, verbose_name='기기 ID'),
        ),
    ]
