# Generated by Django 3.0.8 on 2020-07-23 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('univ', '0002_auto_20200709_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jh',
            name='name',
            field=models.CharField(max_length=255, verbose_name='전형명'),
        ),
    ]
