# Generated by Django 3.0.8 on 2020-08-08 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('univ', '0003_auto_20200723_1831'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jh',
            options={'ordering': ['sj', 'name'], 'verbose_name': '전형', 'verbose_name_plural': '전형'},
        ),
        migrations.AlterModelOptions(
            name='major',
            options={'ordering': ['jh', 'name'], 'verbose_name': '전형별 학과', 'verbose_name_plural': '전형별 학과'},
        ),
        migrations.AlterModelOptions(
            name='sj',
            options={'ordering': ['univ', 'sj'], 'verbose_name': '수시/정시', 'verbose_name_plural': '수시/정시'},
        ),
        migrations.AlterModelOptions(
            name='univ',
            options={'ordering': ['name'], 'verbose_name': '대학', 'verbose_name_plural': '대학'},
        ),
        migrations.AddField(
            model_name='schedule',
            name='is_offline',
            field=models.BooleanField(default=False, verbose_name='대면 시험 여부'),
        ),
    ]
