# Generated by Django 3.0.8 on 2020-07-04 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('univ', '0003_auto_20200705_0021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jh',
            name='like',
        ),
        migrations.RemoveField(
            model_name='major',
            name='like',
        ),
        migrations.RemoveField(
            model_name='univ',
            name='like',
        ),
    ]
